-- Create global_news table
CREATE TABLE IF NOT EXISTS global_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    summary TEXT,
    url TEXT,
    source TEXT,
    country TEXT, -- 'US', 'KR', 'CN', 'JP', 'EU', 'CRYPTO'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE global_news ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public Read News" ON global_news FOR SELECT USING (true);

-- Allow service role insert/update (for crawlers)
CREATE POLICY "Service Role Full Access News" ON global_news USING (true) WITH CHECK (true);
